---

- name: rekall dependencies install
  macports:
    name: "{{item}}"
    state: present
  with_items: "{{ rekall_deps }}"

#- include: gcc.yml

## html5lib requires setuptools version 18.5 or above; please upgrade before installing (you have 8.0)
- block:
    - name: Install recent setuptools inside virtualenv
      pip:
        name: setuptools
        version: 33.1.1
        state: present
        virtualenv: "{{ rekall_virtualenv }}"
        virtualenv_command: "{{ virtualenv_exec }}"
  rescue:
    - include: "google-santa-whitelist.yml type=hash path={{ rekall_virtualenv }}/bin/python3.6 action=whitelist match=White"
    - name: Install recent setuptools inside virtualenv
      pip:
        name: setuptools
        version: 33.1.1
        state: present
        virtualenv: "{{ rekall_virtualenv }}"
        virtualenv_command: "{{ virtualenv_exec }}"

## Result 'ImportError: No module named six.moves'
#  pip: "name=setuptools version=34.3.3 state=present virtualenv={{ rekall_virtualenv }}"
- name: Install recent pip inside virtualenv
  pip:
    name: pip
    version: 9.0.1
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
    virtualenv_command: "{{ virtualenv_exec }}"

## FIXME! {"cmd": "/usr/local/share/env-rekall/bin/pip install rekall", "failed": true, "item": "rekall", "msg": "stdout: Collecting rekall\n  Downloading rekall-1.6.0.zip (301kB)\n    Complete output from command python setup.py egg_info:\n    Traceback (most recent call last):\n      File \"<string>\", line 1, in <module>\n      File \"/private/tmp/pip-build-50syky1k/rekall/setup.py\", line 55\n        print \"Installing rekall-core from local directory.\"\n                                                           ^\n    SyntaxError: Missing parentheses in call to 'print'\n    \n    ----------------------------------------\n\n:stderr: Command \"python setup.py egg_info\" failed with error code 1 in /private/tmp/pip-build-50syky1k/rekall/\n"}
- name: Install rekall inside virtualenv
  pip:
    name: "{{item}}"
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
    virtualenv_command: "{{ virtualenv_exec }}"
  with_items:
    - wheel
    - rekall
## to keep SNI issue at bay on older python
    - urllib3[secure]
- name: Install rekall-agent inside virtualenv
  pip:
    name: "{{item}}"
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
    virtualenv_command: "{{ virtualenv_exec }}"
  with_items:
    - rekall-agent
  when: rekall_with_agent

- name: add symlink to /usr/local/bin
  file:
    src: "{{ rekall_virtualenv }}/bin/rekall"
    dest: "/usr/local/bin/rekall"
    state: link

- name: recover profiles locally
  git:
    repo: https://github.com/google/rekall-profiles.git
    dest: "{{ rekall_profiles }}"
  when: rekall_dl_profiles

