---

- name: rekall dependencies install
  package: name={{ rekall_deps }} state=present
  register: pkg_result
  until: pkg_result is success

- import_tasks: gcc.yml

## html5lib requires setuptools version 18.5 or above; please upgrade before installing (you have 8.0)
- name: Install recent setuptools inside virtualenv
  pip:
    name: setuptools
    version: '49.6.0'
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
    virtualenv_python: "{{ rekall_python | default('python') }}"
  register: pkg_result
  until: pkg_result is success
## Result 'ImportError: No module named six.moves'
#  pip: "name=setuptools version=34.3.3 state=present virtualenv={{ rekall_virtualenv }}"
- name: Install recent pip inside virtualenv
  pip:
    name: pip
    version: '22.0.3'
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
  register: pkg_result
  until: pkg_result is success

- name: Install versioned requirements inside virtualenv
  pip:
    name: pyasn1
    version: 0.4.6
    state: present
    virtualenv: "{{ rekall_virtualenv }}"

- name: RedHat8+ | Force wheel 0.34.1 - pep425tags
  pip:
    name: wheel
    version: 0.34.1
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 8)

- name: Ubuntu 20.04 | Install pybindgen inside virtualenv
  pip:
    name: pybindgen
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20)

- name: Ubuntu 20.04, RHEL8 | Use rekall master - rekall#518
  pip:
    name:
      - "git+https://github.com/google/rekall.git{% if not (rekall_version is defined and rekall_version == 'HEAD') %}@{{ rekall_version | default('55d1925f2df9759a989b35271b4fa48fc54a1c86') }}{% endif %}#egg=rekall-core&subdirectory=rekall-core"  # noqa 204
      - "git+https://github.com/google/rekall.git{% if not (rekall_version is defined and rekall_version == 'HEAD') %}@{{ rekall_version | default('55d1925f2df9759a989b35271b4fa48fc54a1c86') }}{% endif %}#egg=rekall-lib&subdirectory=rekall-lib"  # noqa 204
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
  when: >
    (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20) or
    (ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 8)

- name: Install rekall-agent inside virtualenv
  pip:
    name: "{{ rekallagent_pypi_name }}"
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
  when: rekall_with_agent
  register: pkg_result
  until: pkg_result is success

- name: Install rekall inside virtualenv
  pip:
    name: ['wheel', "{{ rekall_pypi_name }}", 'urllib3[secure]']
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
  register: pkg_result
  until: pkg_result is success

- name: Enforce Future 0.16 in virtualenv - rekall#448
  pip:
    name: future
    state: present
    version: 0.16.0
    virtualenv: "{{ rekall_virtualenv }}"
  register: pkg_result
  until: pkg_result is success

- name: Enforce pyaff4 in virtualenv - rekall#493
  pip:
    name: pyaff4
    state: present
    version: 0.26.post6
    virtualenv: "{{ rekall_virtualenv }}"
  register: pkg_result
  until: pkg_result is success
  when: rekall_version is undefined or rekall_version != 'HEAD'

- name: Ubuntu 20.04, RHEL8 | Install prompt-toolkit 3.0.2
  pip:
    name: prompt-toolkit
    version: 3.0.2
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
  when: >
    (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20) or
    (ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 8)

- name: add symlink to /usr/local/bin
  file:
    src: "{{ rekall_virtualenv }}/bin/rekall"
    dest: "/usr/local/bin/rekall"
    mode: '0755'
    state: link

- name: recover profiles locally
  git:
    repo: https://github.com/google/rekall-profiles.git
    dest: "{{ rekall_profiles }}"
    version: "{{ rekall_profiles_version | default('bd3ed58f5055854c6ce7607f1580388edb1ce223') }}"
  when: rekall_dl_profiles|bool
