---

- name: rekall dependencies install
  macports:
    name: "{{ rekall_deps }}"
    state: present
  register: pkg_result
  until: pkg_result is success

#- include: gcc.yml

## html5lib requires setuptools version 18.5 or above; please upgrade before installing (you have 8.0)
- block:
    - name: Install recent setuptools inside virtualenv
      pip:
        name: setuptools
        version: 33.1.1
        state: present
        virtualenv: "{{ rekall_virtualenv }}"
        virtualenv_command: "{{ virtualenv_exec }}"
      register: pkg_result
      until: pkg_result is success
  rescue:
    - include: "google-santa-whitelist.yml type=hash path={{ rekall_virtualenv }}/bin/python3.6 action=whitelist match=White"
    - name: Install recent setuptools inside virtualenv
      pip:
        name: setuptools
        version: 33.1.1
        state: present
        virtualenv: "{{ rekall_virtualenv }}"
        virtualenv_command: "{{ virtualenv_exec }}"
      register: pkg_result
      until: pkg_result is success

## Result 'ImportError: No module named six.moves'
#  pip: "name=setuptools version=34.3.3 state=present virtualenv={{ rekall_virtualenv }}"
- name: Install recent pip inside virtualenv
  pip:
    name: pip
    version: 9.0.1
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
    virtualenv_command: "{{ virtualenv_exec }}"
  register: pkg_result
  until: pkg_result is success

- name: Install rekall inside virtualenv
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
    virtualenv_command: "{{ virtualenv_exec }}"
  with_items:
    - wheel
    - rekall
## to keep SNI issue at bay on older python
    - urllib3[secure]
  register: pkg_result
  until: pkg_result is success
- name: Install rekall-agent inside virtualenv
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
    virtualenv_command: "{{ virtualenv_exec }}"
  with_items:
    - rekall-agent
  when: rekall_with_agent
  register: pkg_result
  until: pkg_result is success

- name: add symlink to /usr/local/bin
  file:
    src: "{{ rekall_virtualenv }}/bin/rekall"
    dest: "/usr/local/bin/rekall"
    state: link

- name: recover profiles locally
  git:
    repo: https://github.com/google/rekall-profiles.git
    dest: "{{ rekall_profiles }}"
    version: "{{ rekall_profiles_version | default('bd3ed58f5055854c6ce7607f1580388edb1ce223') }}"
  when: rekall_dl_profiles
