---

- name: rekall dependencies install
  package: name={{ rekall_deps }} state=present
  register: pkg_result
  until: pkg_result is success

- include: gcc.yml

## html5lib requires setuptools version 18.5 or above; please upgrade before installing (you have 8.0)
- name: Install recent setuptools inside virtualenv
  pip:
    name: setuptools
    version: 33.1.1
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
    virtualenv_python: "{{ rekall_python | default('python') }}"
  register: pkg_result
  until: pkg_result is success
## Result 'ImportError: No module named six.moves'
#  pip: "name=setuptools version=34.3.3 state=present virtualenv={{ rekall_virtualenv }}"
- name: Install recent pip inside virtualenv
  pip:
    name: pip
    version: '20.1'
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
  register: pkg_result
  until: pkg_result is success

- name: Install versioned requirements inside virtualenv
  pip:
    name: pyasn1
    version: 0.4.6
    state: present
    virtualenv: "{{ rekall_virtualenv }}"

- name: Ubuntu 20.04 | Install pybindgen inside virtualenv
  pip:
    name: pybindgen
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20)

- name: Ubuntu 20.04 | Use rekall master - rekall#518
  pip:
    name:
      - "git+https://github.com/google/rekall.git{% if not (rekall_version is defined and rekall_version == 'HEAD') %}@{{ rekall_version | default('c5d68e31705f4b5bd2581c1d951b7f6983f7089c') }}{% endif %}#egg=rekall-core&subdirectory=rekall-core"
      - "git+https://github.com/google/rekall.git{% if not (rekall_version is defined and rekall_version == 'HEAD') %}@{{ rekall_version | default('c5d68e31705f4b5bd2581c1d951b7f6983f7089c') }}{% endif %}#egg=rekall-lib&subdirectory=rekall-lib"
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20)

- name: Install rekall inside virtualenv
  pip:
    name: ['wheel', "{{ rekall_pypi_name }}", 'urllib3[secure]']
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
  register: pkg_result
  until: pkg_result is success

- name: Install rekall-agent inside virtualenv
  pip:
    name: rekall-agent
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
  when: rekall_with_agent
  register: pkg_result
  until: pkg_result is success

- name: Enforce Future 0.16 in virtualenv - rekall#448
  pip:
    name: future
    state: present
    version: 0.16.0
    virtualenv: "{{ rekall_virtualenv }}"
  register: pkg_result
  until: pkg_result is success
  when: rekall_version is undefined or rekall_version != 'HEAD'

- name: Enforce pyaff4 in virtualenv - rekall#493
  pip:
    name: pyaff4
    state: present
    version: 0.26.post6
    virtualenv: "{{ rekall_virtualenv }}"
  register: pkg_result
  until: pkg_result is success
  when: rekall_version is undefined or rekall_version != 'HEAD'

- name: Ubuntu 20.04 | Ensure active rekall requires pypykatz==0.3.9
  replace:
    dest: "{{ rekall_virtualenv }}/lib/python3.8/site-packages/rekall_core-1.7.3.dev59.dist-info/METADATA"
    regexp: '^Requires-Dist: pypykatz \(==.*\)'
    replace: 'Requires-Dist: pypykatz (==0.3.9)'
  when: >
    (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20) and
    (rekall_version is undefined or rekall_version != 'HEAD')

- name: Ubuntu 20.04 | Install pypykatz 0.3.9 - rekall#526
  pip:
    name: pypykatz
    version: 0.3.9
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
  when: >
    (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20) and
    (rekall_version is undefined or rekall_version != 'HEAD')

# 7.14.0 NOK. Requirement.parse('prompt-toolkit<3.0.0')
- name: Ubuntu 20.04 | Install ipython 7.8 - rekall#513
  pip:
    name: ipython
    version: 7.8.0
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
  when: >
    (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20) and
    (rekall_version is undefined or rekall_version != 'HEAD')

- name: add symlink to /usr/local/bin
  file:
    src: "{{ rekall_virtualenv }}/bin/rekall"
    dest: "/usr/local/bin/rekall"
    state: link

- name: recover profiles locally
  git:
    repo: https://github.com/google/rekall-profiles.git
    dest: "{{ rekall_profiles }}"
    version: "{{ rekall_profiles_version | default('bd3ed58f5055854c6ce7607f1580388edb1ce223') }}"
  when: rekall_dl_profiles|bool
