---

- name: rekall dependencies install
  macports:
    name: "{{ rekall_deps }}"
    state: present
  register: pkg_result
  until: pkg_result is success

# - import_tasks: gcc.yml

## html5lib requires setuptools version 18.5 or above; please upgrade before installing (you have 8.0)
- block:
    - name: Install recent setuptools inside virtualenv
      ansible.builtin.pip:
        name: setuptools
        version: '49.6.0'
        state: present
        virtualenv: "{{ rekall_virtualenv }}"
        virtualenv_command: "{{ virtualenv_exec }}"
      register: pkg_result
      until: pkg_result is success
  rescue:
    - import_tasks: google-santa-whitelist.yml
      vars:
        type: hash
        path: "{{ rekall_virtualenv }}/bin/python3.6"
        action: whitelist
        match: White
    - name: Install recent setuptools inside virtualenv
      ansible.builtin.pip:
        name: setuptools
        version: '49.6.0'
        state: present
        virtualenv: "{{ rekall_virtualenv }}"
        virtualenv_command: "{{ virtualenv_exec }}"
      register: pkg_result
      until: pkg_result is success

## Result 'ImportError: No module named six.moves'
#  pip: "name=setuptools version=34.3.3 state=present virtualenv={{ rekall_virtualenv }}"
- name: Install recent pip inside virtualenv
  ansible.builtin.pip:
    name: pip
    version: '20.2.2'
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
    virtualenv_command: "{{ virtualenv_exec }}"
  register: pkg_result
  until: pkg_result is success

- name: Install rekall inside virtualenv
  ansible.builtin.pip:
    name: ['wheel', 'rekall', 'urllib3[secure]']
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
    virtualenv_command: "{{ virtualenv_exec }}"
  register: pkg_result
  until: pkg_result is success
- name: Install rekall-agent inside virtualenv
  ansible.builtin.pip:
    name: rekall-agent
    state: present
    virtualenv: "{{ rekall_virtualenv }}"
    virtualenv_command: "{{ virtualenv_exec }}"
  when: rekall_with_agent
  register: pkg_result
  until: pkg_result is success

- name: add symlink to /usr/local/bin
  ansible.builtin.file:
    src: "{{ rekall_virtualenv }}/bin/rekall"
    dest: "/usr/local/bin/rekall"
    mode: '0755'
    state: link

- name: recover profiles locally
  ansible.builtin.git:
    repo: https://github.com/google/rekall-profiles.git
    dest: "{{ rekall_profiles }}"
    version: "{{ rekall_profiles_version | default('bd3ed58f5055854c6ce7607f1580388edb1ce223') }}"
  when: rekall_dl_profiles|bool
