---

- name: Include version-specific variables for Ubuntu.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  ansible.builtin.include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"
- name: Include other distribution-specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_os_family == "Alpine" or ansible_distribution == 'MacOSX'

# - import_tasks: pip-upgrade.yml
- import_tasks: rekall.yml
  when: ansible_distribution != 'MacOSX'
- import_tasks: rekall-darwin.yml
  when: ansible_distribution == 'MacOSX'

- import_tasks: rekall-agent-http-server.yml
  when: rekall_with_agentserver|bool
- import_tasks: rekall-agent.yml
  when: rekall_with_agent|bool
