---
- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  pre_tasks:
    - name: Ubuntu | Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16)
    - name: RedHat | Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (yum install -y python3)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8)
    - name: Gather Facts
      ansible.builtin.setup:
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16)
    - name: Ubuntu Bionic+, Redhat 8+ | Enforce python3 for ansible
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3
      when: >
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16) or
        (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8)
    - name: Ubuntu Focal+, Redhat 8+ | Latest rekall version requiring python>=3.7
      ansible.builtin.set_fact:
        rekall_pypi_name: git+https://github.com/google/rekall.git@55d1925f2df9759a989b35271b4fa48fc54a1c86
        rekall_version: 55d1925f2df9759a989b35271b4fa48fc54a1c86
      when: >
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20) or
        (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8)
  tasks:
    - name: "Include juju4.rekall"
      ansible.builtin.include_role:
        name: "juju4.rekall"
