---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Ensure pip packages are installed
      ansible.builtin.command: '/usr/local/share/env-rekall/bin/pip freeze'
      changed_when: false
      register: pfreeze
    - name: Validate config present
      ansible.builtin.assert:
        that: item in pfreeze.stdout
      with_items:
        - ipython
        - efilter
        - pytsk3
        - pyaff4
        - rekall
        - rekall-yara
        - six

    - name: Ensure rekall executable is present
      ansible.builtin.stat:
        path: /usr/local/share/env-rekall/bin/rekall
      register: rek
    - name: Validate rekall present
      ansible.builtin.assert:
        that: rek.stat.exists and rek.stat.size != 0 and rek.stat.mode == '0755'

    - name: Ensure rekall is running
      ansible.builtin.command: /usr/local/share/env-rekall/bin/rekall --version
      register: ps
      changed_when: false
    - name: Validate run output
      ansible.builtin.assert:
        that:
          - ps.stdout
          - "'This is Rekall Version' in ps.stdout"
          - "'pkg_resources.ContextualVersionConflict' not in ps.stderr"
          - "'Error' not in ps.stderr"

    - name: Ensure rekall is running
      ansible.builtin.command: /usr/local/bin/rekall --version
      register: ps2
      changed_when: false
    - name: Validate run output
      ansible.builtin.assert:
        that:
          - ps2.stdout
          - "'This is Rekall Version' in ps2.stdout"
          - "'pkg_resources.ContextualVersionConflict' not in ps2.stderr"
          - "'Error' not in ps2.stderr"
